packages:
    - packages/*

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
    - '@apify/*'
    - '@crawlee/*'

onlyBuiltDependencies:
    - "@swc/core"
    - esbuild
    - playwright
    - playwright-core
    - puppeteer

overrides:
    std-env: "^3.10.0"
