name: docs

on:
    push:
        branches:
            - stable

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   name: Use Node.js 16
                uses: actions/setup-node@v2-beta
                with:
                    node-version: 16

            -   name: Set git identity
                run: |
                    git config --global user.name "Jindřich Bär"
                    git config --global user.email "jindrichbar@apify.com"

            -   name: Build & deploy docs
                run: |
                    # install project deps
                    npm install
                    # go to website dir
                    cd website
                    # install website deps
                    npm install
                    # build and deploy the docs
                    npm run deploy
                env:
                    GIT_USER: "barjin:${{ secrets.GH_TOKEN }}"
                    GH_TOKEN: ${{ secrets.GH_TOKEN }}